name: Update number.txt every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes

jobs:
  update-number:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "ArvindChaturvedi"
        git config --global user.email "Arvind.Chaturvedi1092@gmail.com"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Run Python script
      run: python update_number.py

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ArvindChaturvedi/scripts.git
        git fetch origin
        git rebase origin/main  # Pull latest changes
        git push origin main
